SAP/jmc

- .github/workflows/validate.yml
- scripts/checkformatting.bat
- scripts/checkformatting.sh
- scripts/runagenttests.bat
- scripts/runagenttests.sh
- scripts/runapptests.bat
- scripts/runapptests.sh
- scripts/runcoretests.bat
- scripts/runcoretests.sh
- scripts/startp2.bat
- scripts/startp2.sh
Please merge latest commit 0889d60dea0cd6c2f6bc29ca8fb84ccf4758d1df from jmc upstream repo into branch sap
> sap: Merge 0889d60dea0cd6c2f6bc29ca8fb84ccf4758d1df

- agent/pom.xml
- agent/src/test/resources/org/openjdk/jmc/agent/test/failing_control_permission.policy
- core/tests/org.openjdk.jmc.common.test/.classpath
- core/tests/org.openjdk.jmc.common.test/build.properties
- core/tests/org.openjdk.jmc.common.test/pom.xml
- scripts/runagenttests.bat
- scripts/runagenttests.sh
Please merge latest commit b5e03c6761aaf70e21374068d5fb6a4a4ad8d4f2 from jmc upstream repo into branch sap
> sap: Merge b5e03c6761aaf70e21374068d5fb6a4a4ad8d4f2

- configuration/ide/eclipse/launchers/JMC-RCP-plug-ins.launch
- configuration/ide/eclipse/launchers/JMC-RCP.launch
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkAttributes.java
- releng/platform-definitions/platform-definition-2021-06/platform-definition-2021-06.target
- releng/platform-definitions/platform-definition-2021-09/platform-definition-2021-09.target
- releng/platform-definitions/platform-definition-2021-12/platform-definition-2021-12.target
- releng/platform-definitions/platform-definition-2022-03/platform-definition-2022-03.target
- releng/platform-definitions/platform-definition-2022-06/platform-definition-2022-06.target
- releng/third-party/pom.xml
Please merge latest commit 7606e1c4fdbe9a3f1745ef4d2b5f8403e25484af from jmc upstream repo into branch sap
> sap: Merge 7606e1c4fdbe9a3f1745ef4d2b5f8403e25484af

- application/org.openjdk.jmc.flightrecorder.flameview/pom.xml
- application/org.openjdk.jmc.flightrecorder.flameview/src/main/java/org/openjdk/jmc/flightrecorder/flameview/views/FlameGraphView.java
- license/THIRDPARTYREADME.txt
- releng/platform-definitions/platform-definition-2022-06/platform-definition-2022-06.target
Please merge latest commit eabb8615a3f73360626374748b36324f77a6cef3 from jmc upstream repo into branch sap
> sap: Merge eabb8615a3f73360626374748b36324f77a6cef3

- core/org.openjdk.jmc.flightrecorder.rules.jdk/src/main/java/org/openjdk/jmc/flightrecorder/rules/jdk/memory/StringDeduplicationRule.java
- core/org.openjdk.jmc.flightrecorder.rules/src/main/java/org/openjdk/jmc/flightrecorder/rules/report/html/internal/RulesHtmlToolkit.java
- core/org.openjdk.jmc.flightrecorder.rules/src/main/resources/org/openjdk/jmc/flightrecorder/rules/report/html/internal/rules_overview.html
- core/tests/org.openjdk.jmc.flightrecorder.rules.jdk.test/src/test/resources/baseline/JfrRuleBaseline.xml
Please merge latest commit bfa2e068986bd10ca05b189fe7146a9d8f09016a from jmc upstream repo into branch sap8
> sap8: Merge bfa2e068986bd10ca05b189fe7146a9d8f09016a

- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/BinaryScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/DecimalPrefix.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/DecimalScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/DecimalUnitSelector.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/IScalarAffineTransform.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/ImpreciseScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/LongPostOffsetTransform.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/LongPreOffsetTransform.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/LongScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/ScalarQuantity.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/ScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/SimpleAffineTransform.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/UnitLookup.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/internal/parser/ParserStats.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/internal/util/DisjointBuilder.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkAggregators.java
- core/tests/org.openjdk.jmc.common.test/src/main/java/org/openjdk/jmc/common/test/unit/AdHocQuantityTest.java
- core/tests/org.openjdk.jmc.common.test/src/main/java/org/openjdk/jmc/common/test/unit/DecimalPrefixTest.java
Please merge latest commit 68387c5bd454fcf4bdda07d0cbe8d6eb59e2a840 from jmc upstream repo into branch sap
> sap: Merge 68387c5bd454fcf4bdda07d0cbe8d6eb59e2a840

- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/BinaryScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/DecimalScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/IScalarAffineTransform.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/ImpreciseScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/LongPostOffsetTransform.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/LongPreOffsetTransform.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/LongScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/ScalarQuantity.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/ScaleFactor.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/unit/SimpleAffineTransform.java
Please merge latest commit 761797e6990e3588331250a41695b4ba978eba90 from jmc upstream repo into branch sap
> sap: Merge 761797e6990e3588331250a41695b4ba978eba90

- .github/workflows/build.yml
This will fix the build workflow.
> Bump version of dev-drprasad/delete-tag-and-release

- build.bat
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/IMCFrame.java
Please merge latest commit 1fb69d47fa54bbf98e2463c0b07be2272b6f8a87 from jmc upstream repo into branch sap
> sap: Merge 1fb69d47fa54bbf98e2463c0b07be2272b6f8a87

- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/item/Aggregators.java
- core/org.openjdk.jmc.flightrecorder.rules.jdk/META-INF/MANIFEST.MF
- core/org.openjdk.jmc.flightrecorder.rules/META-INF/MANIFEST.MF
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkAggregators.java
- pom.xml
- releng/platform-definitions/platform-definition-2022-03/platform-definition-2022-03.target
- releng/platform-definitions/platform-definition-2022-09/platform-definition-2022-09.target
- releng/platform-definitions/platform-definition-2022-12/platform-definition-2022-12.target
- releng/platform-definitions/platform-definition-2023-03/.project
- releng/platform-definitions/platform-definition-2023-03/platform-definition-2023-03.target
- releng/platform-definitions/platform-definition-2023-03/pom.xml
Please merge latest commit 58c9ede2aa1fb5c966f588f6576514ff0802e002 from jmc upstream repo into branch sap
> sap: Merge 58c9ede2aa1fb5c966f588f6576514ff0802e002

- application/org.openjdk.jmc.ui/src/main/java/org/openjdk/jmc/ui/charts/XYChart.java
- application/org.openjdk.jmc.ui/src/main/java/org/openjdk/jmc/ui/misc/ChartCanvas.java
- application/org.openjdk.jmc.ui/src/main/java/org/openjdk/jmc/ui/misc/ChartTextCanvas.java
- core/org.openjdk.jmc.flightrecorder.rules.jdk/src/main/java/org/openjdk/jmc/flightrecorder/rules/jdk/memory/GcPauseTargetRule.java
- core/org.openjdk.jmc.flightrecorder.rules.jdk/src/main/java/org/openjdk/jmc/flightrecorder/rules/jdk/messages/internal/Messages.java
- core/org.openjdk.jmc.flightrecorder.rules.jdk/src/main/resources/META-INF/services/org.openjdk.jmc.flightrecorder.rules.IRule
- core/org.openjdk.jmc.flightrecorder.rules.jdk/src/main/resources/org/openjdk/jmc/flightrecorder/rules/jdk/messages/internal/messages.properties
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkAttributes.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkFilters.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkTypeIDs.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/messages/internal/Messages.java
- core/org.openjdk.jmc.flightrecorder/src/main/resources/org/openjdk/jmc/flightrecorder/jdk/messages/internal/messages.properties
- core/tests/org.openjdk.jmc.flightrecorder.rules.jdk.test/src/main/resources/baseline/JfrRuleBaseline.xml
- releng/platform-definitions/platform-definition-2022-09/platform-definition-2022-09.target
- releng/platform-definitions/platform-definition-2022-12/platform-definition-2022-12.target
- releng/platform-definitions/platform-definition-2023-03/platform-definition-2023-03.target
- releng/third-party/.classpath
- releng/third-party/pom.xml
Please merge latest commit 84ac8224ee87cc16eccc2deefb6cad03e42153b5 from jmc upstream repo into branch sap
> sap: Merge 84ac8224ee87cc16eccc2deefb6cad03e42153b5

- application/tests/org.openjdk.jmc.rjmx.services.jfr.test/src/test/java/org/openjdk/jmc/rjmx/services/jfr/test/EventTemplateTest.java
- core/tests/org.openjdk.jmc.flightrecorder.rules.test/.classpath
Please merge latest commit 5ace151b6dc00096b5b3212edfad40e86f8bcf8d from jmc upstream repo into branch sap
> sap: Merge 5ace151b6dc00096b5b3212edfad40e86f8bcf8d

- application/org.openjdk.jmc.console.agent/src/main/java/org/openjdk/jmc/console/agent/manager/model/Preset.java
- application/org.openjdk.jmc.console.agent/src/main/java/org/openjdk/jmc/console/agent/utils/ProbeValidator.java
- releng/tools/org.openjdk.jmc.util.releasenotes/src/org/openjdk/jmc/utils/releasenotes/Transform.java
Please merge latest commit 5b2270f450af025054b6caa396ba7881f97f4fe8 from jmc upstream repo into branch sap8
> sap8: Merge 5b2270f450af025054b6caa396ba7881f97f4fe8

- application/org.openjdk.jmc.console.agent/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.console.jconsole/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.console.jconsole/src/main/java/org/openjdk/jmc/console/jconsole/tabs/JConsoleTab.java
- application/org.openjdk.jmc.console.ui.diagnostic/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.console.ui.diagnostic/src/main/java/org/openjdk/jmc/console/ui/diagnostic/form/DiagnosticTab.java
- application/org.openjdk.jmc.console.ui.mbeanbrowser/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.console.ui.mbeanbrowser/src/main/java/org/openjdk/jmc/console/ui/mbeanbrowser/tab/MBeanTab.java
- application/org.openjdk.jmc.console.ui.notification/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.console.ui.notification/src/main/java/org/openjdk/jmc/console/ui/notification/TriggerTab.java
- application/org.openjdk.jmc.console.ui.subscriptions/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.console.ui.subscriptions/src/main/java/org/openjdk/jmc/console/ui/subscriptions/SubscriptionTab.java
- application/org.openjdk.jmc.console.ui/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.console.ui/src/main/java/org/openjdk/jmc/console/ui/editor/internal/ConsoleEditor.java
- application/org.openjdk.jmc.console.ui/src/main/java/org/openjdk/jmc/console/ui/editor/internal/ConsoleFormPage.java
- application/org.openjdk.jmc.console.ui/src/main/java/org/openjdk/jmc/console/ui/tabs/memory/MemoryTab.java
- application/org.openjdk.jmc.console.ui/src/main/java/org/openjdk/jmc/console/ui/tabs/overview/OverviewTab.java
- application/org.openjdk.jmc.console.ui/src/main/java/org/openjdk/jmc/console/ui/tabs/system/SystemTab.java
- application/org.openjdk.jmc.console.ui/src/main/java/org/openjdk/jmc/console/ui/tabs/threads/ThreadTab.java
- application/org.openjdk.jmc.rcp.intro/content/root.xhtml
- application/pom.xml
- pom.xml
- releng/platform-definitions/platform-definition-2022-09/platform-definition-2022-09.target
- releng/platform-definitions/platform-definition-2022-12/platform-definition-2022-12.target
- releng/platform-definitions/platform-definition-2023-09/platform-definition-2023-09.target
- releng/platform-definitions/platform-definition-2023-12/platform-definition-2023-12.target
- releng/platform-definitions/platform-definition-2023-12/pom.xml
- releng/pom.xml
- releng/third-party/pom.xml
Please merge latest commit ea0b1133ebe0c87e2a31ccb1de6a1354408f4350 from jmc upstream repo into branch sap
> sap: Merge ea0b1133ebe0c87e2a31ccb1de6a1354408f4350

- application/uitests/org.openjdk.jmc.flightrecorder.uitest/src/test/java/org/openjdk/jmc/flightrecorder/uitest/ControlRecordingsTest.java
Please merge latest commit 0d823a9fc7540e942da16e853836a563a8fde323 from jmc upstream repo into branch sap
> sap: Merge 0d823a9fc7540e942da16e853836a563a8fde323

- scripts/checkcopyrightyear.sh
Please merge latest commit 110de0673ad794db78ad163962f33747aa20dc20 from jmc upstream repo into branch sap
> sap: Merge 110de0673ad794db78ad163962f33747aa20dc20

- application/org.openjdk.jmc.console.agent/src/main/java/org/openjdk/jmc/console/agent/manager/wizards/PresetManagerPage.java
- application/org.openjdk.jmc.flightrecorder.controlpanel.ui/src/main/java/org/openjdk/jmc/flightrecorder/controlpanel/ui/wizards/TemplateEditPage.java
- application/org.openjdk.jmc.flightrecorder.flamegraph/src/main/java/org/openjdk/jmc/flightrecorder/flamegraph/views/FlamegraphSwingView.java
Please merge latest commit d0fb28ffb5a22fad4e33b02abfd782a5caa89ab8 from jmc upstream repo into branch sap
> sap: Merge d0fb28ffb5a22fad4e33b02abfd782a5caa89ab8

- agent/pom.xml
Please merge latest commit 57e386adb82b81d228a5f5ab114ef02c28cc8930 from jmc upstream repo into branch sap
> sap: Merge 57e386adb82b81d228a5f5ab114ef02c28cc8930

- application/org.openjdk.jmc.browser.attach/src/main/java/org/openjdk/jmc/browser/attach/LocalJVMToolkit.java
- application/org.openjdk.jmc.browser.attach/src/main/java/org/openjdk/jmc/browser/attach/internal/ExecuteTunnler.java
- application/org.openjdk.jmc.browser.attach/src/main/java/org/openjdk/jmc/browser/attach/internal/MonitoredHostWrapper.java
- application/org.openjdk.jmc.browser.attach/src/main/java/org/openjdk/jmc/browser/attach/internal/MonitoredVmWrapper.java
Please merge latest commit 92750098a2deac54b8165ec5c6d368be00707856 from jmc upstream repo into branch sap
> sap: Merge 92750098a2deac54b8165ec5c6d368be00707856

- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/internal/parser/v1/TypeManager.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/internal/util/JfrInternalConstants.java
Please merge latest commit ad0ef9e72d6a6495ad63a629ce83958e1a44876b from jmc upstream repo into branch sap
> sap: Merge ad0ef9e72d6a6495ad63a629ce83958e1a44876b

- application/org.openjdk.jmc.feature.flightrecorder/feature.xml
- application/org.openjdk.jmc.feature.ide/feature.xml
- application/org.openjdk.jmc.flightrecorder.ui/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.flightrecorder.ui/src/main/java/org/openjdk/jmc/flightrecorder/ui/pages/JVMInformationPage.java
- application/org.openjdk.jmc.flightrecorder.ui/src/main/java/org/openjdk/jmc/flightrecorder/ui/websocket/WebsocketServer.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/item/Aggregators.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkAggregators.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/parser/synthetic/SyntheticAttributeExtension.java
- pom.xml
- releng/platform-definitions/platform-definition-2024-03/.project
- releng/platform-definitions/platform-definition-2024-03/platform-definition-2024-03.target
- releng/platform-definitions/platform-definition-2024-03/pom.xml
- releng/third-party/pom.xml
- releng/tools/org.openjdk.jmc.util.listversions/src/org/openjdk/jmc/util/listversions/ListVersions.java
Please merge latest commit 992333a5259cfbcf0db1a08cc34936d189c962e3 from jmc upstream repo into branch sap
> sap: Merge 992333a5259cfbcf0db1a08cc34936d189c962e3

- application/coverage/pom.xml
- application/org.openjdk.jmc.feature.core/feature.xml
- application/org.openjdk.jmc.jolokia/.classpath
- application/org.openjdk.jmc.jolokia/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.jolokia/OSGI-INF/l10n/bundle.properties
- application/org.openjdk.jmc.jolokia/build.properties
- application/org.openjdk.jmc.jolokia/plugin.xml
- application/org.openjdk.jmc.jolokia/pom.xml
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JmcJolokiaJmxConnection.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JmcJolokiaJmxConnectionProvider.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JmcJolokiaJmxConnector.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JmcJolokiaPlugin.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/Messages.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/messages.properties
- application/org.openjdk.jmc.rjmx/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.rjmx/src/main/java/org/openjdk/jmc/rjmx/internal/ProtocolInitializer.java
- application/org.openjdk.jmc.rjmx/src/main/java/org/openjdk/jmc/rjmx/internal/ServerHandle.java
- application/pom.xml
- application/tests/org.openjdk.jmc.jolokia.test/.classpath
- application/tests/org.openjdk.jmc.jolokia.test/META-INF/MANIFEST.MF
- application/tests/org.openjdk.jmc.jolokia.test/build.properties
- application/tests/org.openjdk.jmc.jolokia.test/pom.xml
- application/tests/org.openjdk.jmc.jolokia.test/src/test/java/org/openjdk/jmc/jolokia/JolokiaTest.java
- application/tests/pom.xml
- core/org.openjdk.jmc.rjmx.common/.classpath
- core/org.openjdk.jmc.rjmx.common/src/main/java/org/openjdk/jmc/rjmx/common/internal/RJMXConnection.java
- pom.xml
- releng/platform-definitions/platform-definition-2024-03/platform-definition-2024-03.target
- releng/third-party/pom.xml
- scripts/checkcopyrightyear.sh
Please merge latest commit 8332466230197b029db2d4f1e9c8f5c8faba65a0 from jmc upstream repo into branch sap
> sap: Merge 8332466230197b029db2d4f1e9c8f5c8faba65a0

- license/THIRDPARTYREADME.txt
- releng/platform-definitions/platform-definition-2024-03/platform-definition-2024-03.target
- releng/third-party/pom.xml
Please merge latest commit 37dcf0a3bd7ee5c9b5cc8c507c8554e292a45125 from jmc upstream repo into branch sap
> sap: Merge 37dcf0a3bd7ee5c9b5cc8c507c8554e292a45125

- application/org.openjdk.jmc.console.agent/src/main/java/org/openjdk/jmc/console/agent/manager/model/Preset.java
- application/org.openjdk.jmc.jolokia/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.jolokia/plugin.xml
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/AbstractCachedDescriptorProvider.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JmcJolokiaJmxConnectionProvider.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JmcJolokiaPlugin.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JolokiaAgentDescriptor.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JolokiaDiscoveryListener.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/JolokiaDiscoverySettings.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/ServerConnectionDescriptor.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/messages.properties
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/preferences/JolokiaPreferencePage.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/preferences/Messages.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/preferences/PreferenceConstants.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/preferences/PreferenceInitializer.java
- application/org.openjdk.jmc.jolokia/src/main/java/org/openjdk/jmc/jolokia/preferences/messages.properties
- application/tests/org.openjdk.jmc.jolokia.test/META-INF/MANIFEST.MF
- application/tests/org.openjdk.jmc.jolokia.test/pom.xml
- application/tests/org.openjdk.jmc.jolokia.test/src/test/java/org/openjdk/jmc/jolokia/JolokiaTest.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/util/XmlToolkit.java
- core/org.openjdk.jmc.flightrecorder.configuration/src/main/java/org/openjdk/jmc/flightrecorder/configuration/model/xml/XMLModel.java
- core/tests/org.openjdk.jmc.flightrecorder.rules.jdk.test/src/main/java/org/openjdk/jmc/flightrecorder/test/rules/jdk/TestRulesWithJfr.java
- releng/platform-definitions/platform-definition-2024-03/platform-definition-2024-03.target
- releng/third-party/pom.xml
- releng/tools/org.openjdk.jmc.util.listversions/src/org/openjdk/jmc/util/listversions/ListVersions.java
- releng/tools/org.openjdk.jmc.util.releasenotes/src/org/openjdk/jmc/utils/releasenotes/Transform.java
Please merge latest commit 5016cc1919616f559cec95a20dc3ae2edb721dc3 from jmc upstream repo into branch sap
> sap: Merge 5016cc1919616f559cec95a20dc3ae2edb721dc3

- core/org.openjdk.jmc.flightrecorder.writer/src/main/java/org/openjdk/jmc/flightrecorder/writer/AnnotationValueObject.java
- core/org.openjdk.jmc.flightrecorder.writer/src/main/java/org/openjdk/jmc/flightrecorder/writer/RecordingImpl.java
- core/org.openjdk.jmc.flightrecorder.writer/src/main/java/org/openjdk/jmc/flightrecorder/writer/api/Recording.java
- core/tests/org.openjdk.jmc.flightrecorder.writer.test/src/main/java/org/openjdk/jmc/flightrecorder/writer/RecordingImplTest.java
Please merge latest commit 4c9d9e47bcf13d6c12ddfcdeddb2e90dbe3b691b from jmc upstream repo into branch sap
> sap: Merge 4c9d9e47bcf13d6c12ddfcdeddb2e90dbe3b691b

- application/uitests/org.openjdk.jmc.flightrecorder.uitest/src/test/java/org/openjdk/jmc/flightrecorder/uitest/ControlRecordingsTest.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/internal/parser/v1/TypeManager.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/internal/parser/v1/ValueReaders.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkAttributes.java
Please merge latest commit 719b71422e06d6d290642c97e48dbef22b437449 from jmc upstream repo into branch sap
> sap: Merge 719b71422e06d6d290642c97e48dbef22b437449

- .github/workflows/validate.yml
- agent/src/main/java/org/openjdk/jmc/agent/impl/ResolvedConvertable.java
- agent/src/test/java/org/openjdk/jmc/agent/converters/test/GurkMultiDefaultConverter.java
- agent/src/test/java/org/openjdk/jmc/agent/converters/test/InstrumentMeConverter.java
- agent/src/test/resources/org/openjdk/jmc/agent/converters/test/jfrprobes_template.xml
- application/org.openjdk.jmc.jolokia/plugin.xml
- pom.xml
- releng/platform-definitions/platform-definition-2024-06/platform-definition-2024-06.target
- releng/platform-definitions/platform-definition-2024-06/pom.xml
- releng/third-party/pom.xml
- releng/tools/org.openjdk.jmc.util.listversions/src/org/openjdk/jmc/util/listversions/ListVersions.java
- releng/tools/org.openjdk.jmc.util.listversions/src/org/openjdk/jmc/util/listversions/UpdateVersions.java
Please merge latest commit 4aa38c7a555fdb71d15cf757a70ef9aada0bd347 from jmc upstream repo into branch sap
> sap: Merge 4aa38c7a555fdb71d15cf757a70ef9aada0bd347

- application/org.openjdk.jmc.flightrecorder.graphview/pom.xml
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkAttributes.java
- releng/platform-definitions/platform-definition-2024-03/platform-definition-2024-03.target
- releng/platform-definitions/platform-definition-2024-06/platform-definition-2024-06.target
- releng/third-party/pom.xml
Please merge latest commit eead0934233e3d01839faf6e71bb6ae8985ee5f9 from jmc upstream repo into branch sap
> sap: Merge eead0934233e3d01839faf6e71bb6ae8985ee5f9

- application/org.openjdk.jmc.console.agent/src/main/java/org/openjdk/jmc/console/agent/manager/model/Preset.java
- core/org.openjdk.jmc.common/src/main/java/org/openjdk/jmc/common/util/XmlToolkit.java
- core/org.openjdk.jmc.flightrecorder.configuration/src/main/java/org/openjdk/jmc/flightrecorder/configuration/model/xml/XMLModel.java
- core/tests/org.openjdk.jmc.flightrecorder.rules.jdk.test/src/main/java/org/openjdk/jmc/flightrecorder/test/rules/jdk/TestRulesWithJfr.java
- releng/tools/org.openjdk.jmc.util.listversions/src/org/openjdk/jmc/util/listversions/ListVersions.java
Please merge latest commit cf85dbcb3872bd31c7d8145833eacda148455b3e from jmc upstream repo into branch sap
> sap: Merge cf85dbcb3872bd31c7d8145833eacda148455b3e

- configuration/ide/eclipse/launchers/JMC-Eclipse-plug-ins.launch
- configuration/ide/eclipse/launchers/JMC-Eclipse.launch
- configuration/ide/eclipse/launchers/JMC-RCP-plug-ins.launch
Please merge latest commit f67ead33fa3f2c16bd747907124a8d27e160085e from jmc upstream repo into branch sap
> sap: Merge f67ead33fa3f2c16bd747907124a8d27e160085e

- application/org.openjdk.jmc.feature.core/feature.xml
- application/org.openjdk.jmc.feature.ide/feature.xml
- application/org.openjdk.jmc.feature.license/feature.properties
- application/org.openjdk.jmc.flightrecorder.ui/META-INF/MANIFEST.MF
- application/org.openjdk.jmc.jolokia/META-INF/MANIFEST.MF
Please merge latest commit 39a795dd515cc37c0a5110456bf9aeedc13c77ea from jmc upstream repo into branch sap
> sap: Merge 39a795dd515cc37c0a5110456bf9aeedc13c77ea

- core/org.openjdk.jmc.flightrecorder.rules/src/main/java/org/openjdk/jmc/flightrecorder/rules/report/JfrRulesReport.java
- core/org.openjdk.jmc.flightrecorder/src/main/java/org/openjdk/jmc/flightrecorder/jdk/JdkQueries.java
Please merge latest commit 77713a0062c386b71d3875ce5f9d729a55c2f6e2 from jmc upstream repo into branch sap
> sap: Merge 77713a0062c386b71d3875ce5f9d729a55c2f6e2

- application/org.openjdk.jmc.rjmx.ext/META-INF/MANIFEST.MF
Please merge latest commit 9725f58b925c741fd9ba2aa2902ffe91ab2d474f from jmc upstream repo into branch sap
> sap: Merge 9725f58b925c741fd9ba2aa2902ffe91ab2d474f

- application/org.openjdk.jmc.ui.common/src/main/java/org/openjdk/jmc/ui/common/security/SecureStore.java
- application/org.openjdk.jmc.ui.common/src/main/resources/preferences.properties
Please merge latest commit 2458719dcc9bc11e94fb21226f6e5e0f1bdab740 from jmc upstream repo into branch sap
> sap: Merge 2458719dcc9bc11e94fb21226f6e5e0f1bdab740

- application/org.openjdk.jmc.console.ui/src/main/java/org/openjdk/jmc/console/ui/editor/internal/ConsoleEditor.java
- application/org.openjdk.jmc.flightrecorder.ui/src/main/java/org/openjdk/jmc/flightrecorder/ui/views/stacktrace/StacktraceView.java
- application/org.openjdk.jmc.rjmx/src/main/java/org/openjdk/jmc/rjmx/internal/ServerHandle.java
- core/org.openjdk.jmc.flightrecorder.rules.jdk/src/main/java/org/openjdk/jmc/flightrecorder/rules/jdk/general/OptionsCheckRule.java
- core/org.openjdk.jmc.rjmx.common/src/main/java/org/openjdk/jmc/rjmx/common/ConnectionToolkit.java
- core/org.openjdk.jmc.rjmx.common/src/main/java/org/openjdk/jmc/rjmx/common/internal/DefaultConnectionHandle.java
Please merge latest commit dd6fd901e3ee4fdd766a2b4dfe43bcc1388fbf2a from jmc upstream repo into branch sap
> sap: Merge dd6fd901e3ee4fdd766a2b4dfe43bcc1388fbf2a

- README.md
- application/org.openjdk.jmc.rcp.product/jmc.product
- application/uitests/org.openjdk.jmc.rcp.application.uitest/src/test/java/org/openjdk/jmc/rcp/application/uitest/UpdateSiteTest.java
- core/org.openjdk.jmc.flightrecorder.rules/src/main/java/org/openjdk/jmc/flightrecorder/rules/report/html/internal/RulesHtmlToolkit.java
Please merge latest commit 25b8e1d15d1f49f11ae021178e173b5346c4ed4b from jmc upstream repo into branch sap
> sap: Merge 25b8e1d15d1f49f11ae021178e173b5346c4ed4b
